apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color-cluster01
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/fabricioveronez/aula-app-of-apps
    path: webcolors
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:    
    - CreateNamespace=true 