apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color-cluster01
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/fabricioveronez/web-color-deploy
    path: k8s
    targetRevision: HEAD
  destination:
    namespace: web-color
    server: https://k8s1-ruq9nmue.hcp.eastus.azmk8s.io:443
  project: default
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:    
    - CreateNamespace=true 