apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-color-multi-cluster
  namespace: argocd
spec: 
  generators:
  - matrix:
      generators:
      - list:
          elements:
            - environment: dev
            - environment: prod
      - clusters: {}
  template:
    metadata:
      name: 'web-color-{{name}}-{{environment}}'
    spec:
      source:
        repoURL: https://github.com/fabricioveronez/web-color-deploy
        path: k8s/{{environment}}
        targetRevision: HEAD
      destination:
        namespace: 'webcolor-{{environment}}'
        server: '{{server}}'
      project: default
      syncPolicy:
        automated: 
          prune: true 
          selfHeal: true 
        syncOptions:    
        - CreateNamespace=true 