apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-color-multi-cluster
  namespace: argocd
spec: 
  generators:
  - list:
      elements:
        - cluster: cluster01
          url: https://kubernetes.default.svc
          region: us
          namespace: webcolor
        - cluster: cluster02
          url: https://192.168.1.53:6443
          region: br
          namespace: webcolor
  template:
    metadata:
      name: 'web-color-{{region}}-{{cluster}}'
    spec:
      source:
        repoURL: https://github.com/iadocicco-ale/web-color-deploy
        path: k8s
        targetRevision: HEAD
      destination:
        namespace: '{{namespace}}'
        server: '{{url}}'
      project: default
      syncPolicy:
        automated: 
          prune: true 
          selfHeal: true 
        syncOptions:    
        - CreateNamespace=true 