apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-color-multi-cluster
  namespace: argocd
spec: 
  generators:
    - clusters: 
        matchExpressions:
          - key: deploy
            operator: In
            values: 
              - "true"
  template:
    metadata:
      name: 'web-color-{{name}}'
    spec:
      source:
        repoURL: https://github.com/fabricioveronez/web-color-deploy
        path: k8s
        targetRevision: HEAD
      destination:
        namespace: webcolor
        server: '{{server}}'
      project: default
      syncPolicy:
        automated: 
          prune: true 
          selfHeal: true 
        syncOptions:    
        - CreateNamespace=true 